# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJx3gZHftk3AJDr76LOF1my-b8Tg_NbO
"""

print("hello world")

!python --version

# Commented out IPython magic to ensure Python compatibility.
# %pip list

# Commented out IPython magic to ensure Python compatibility.
# %pip install PySide6

import numpy as np
import pandas as pd

df = pd.read_csv("/content/data.csv")
df

import torch
import numpy as np
import pandas as pd

a = torch.empty(5,3,2)

print(a)

b = torch.zeros(5,3,7)

print(b)

a = torch.rand(5,3)
print(a)

a = torch.tensor(([7,2],[4,8]))
print(a)

print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'
device

# Tensors can be created in GPU memory
a = torch.Tensor([[1,2],[3,4]]).to(device)
print(a)

b = torch.rand(2, 2, requires_grad=True)

print(b)

x = torch.zeros(2, 2, requires_grad=True)
y = x + 3
z = y**2
out = z.mean()
print(y)
print(z)
print(out)

out.backward()

print(x.grad)

# ----------------Task---------------

x = torch.tensor([[1.,2.],[3.,4.]], requires_grad=True)
print(z)
z = x**2
print(z)
z.backward (torch.ones(2,2))

print(x.grad)

a = torch.tensor([2,2])

x = torch.rand(1,1, requires_grad=True)
a = x.to(dtype=torch.float32)

if x% 2==0:
  d = a**2
else:
  d = a**3
  print(d)

g = (d * torch.rand(1,1))
print(g)

h = torch.exp(g)
print(h)

h.backward()
print(x.grad)